apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q1rw3rdvo-nodejs 
  janus-idp.io/tekton: q1rw3rdvo-nodejs
  backstage.io/kubernetes-id: q1rw3rdvo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q1rw3rdvo-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  